FROM elixir:1.4.2

ADD fixtures /fixtures
ADD scripts /scripts

# Install nodeJS
RUN apt-get update \
    && apt-get -y install curl \
    && curl -sL https://deb.nodesource.com/setup_7.x | bash - \
    && apt-get install -y nodejs

# Install hex and rebar
RUN mix local.hex --force \
    && mix local.rebar --force

# Install python pip
RUN apt-get -y install python3-pip

# Install python dependencies
RUN pip3 install -r /fixtures/requirements.txt
