version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aion
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  aion:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - AION_DB_HOSTNAME="db"
    command: bash /scripts/run_server
    volumes:
      - ./aion/:/aion
      - /aion/deps
      - /aion/node_modules
    ports:
      - "4000:4000"
