#!/bin/sh
TMP="precommithookerrorfile"

cd aion

mix credo --strict >"$TMP" 2>/dev/null || {
  echo "[PRE-COMMIT] Elixir linter has failed:"
  cat "$TMP"
  rm -f "$TMP"
  exit 1
}

node-modules/elm-format/bin/elm-format --yes --validate web/elm/src >"$TMP" 2>/dev/null || {
  echo '[PRE-COMMIT HOOK] elm-format has failed:'
  cat "$TMP"
  rm -f "$TMP"
  exit 1
}


rm -f "$TMP"
