#!/bin/sh
TMP="pre_commit_hook_error_file"

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

function print_success {
  printf "${GREEN}$1${NC}\n"
}

function print_error {
  printf "${RED}$1${NC}\n"
}

function exit_with_errors {
  cat "$TMP"
  rm -f "$TMP"
  exit 1
}

cd aion

#printf "Running dialyzer, may take a while if PLT compilation is needed...\n"
#mix dialyzer --halt-exit-status >"$TMP" 2>/dev/null || {
#  print_error "[PRE-COMMIT] Dialyzer has failed with the following result:"
#  exit_with_errors
#}

printf "Running credo...\n"
mix credo --strict >"$TMP" 2>/dev/null || {
  print_error "[PRE-COMMIT] Elixir linter has failed:"
  exit_with_errors
}


ELM_FORMAT_PATH="node_modules/elm-format/bin/elm-format"
if [ -x $ELM_FORMAT_PATH ]
then
  print_success "Found elm-format in $ELM_FORMAT_PATH" 
else
  print_error "[PRE-COMMIT] elm-format not found in $ELM_FORMAT_PATH. Please make sure you've run make local-deps"
  exit_with_errors
fi

printf "Running elm-format...\n"
$ELM_FORMAT_PATH --yes --validate web/elm/src >"$TMP" 2>/dev/null || {
  print_error '[PRE-COMMIT] elm-format has failed:'
  exit_with_errors
}

rm -f "$TMP"
print_success "All pre-commit hooks have succeeded, good job!"
